# template for server
app:
  host-url: http://localhost
spring:
  profiles:
    include: test, test-h2
  config:
    import: optional:file:.env[.properties]
  datasource:
#    url: jdbc:postgresql://localhost:5432/jira
    url: ${DB_URL}
#    username: jira
    username: ${DB_USERNAME}
#    password: JiraRush
    password: ${DB_PASSWORD}

